resource_group_name = "rg-app-service-ci-01"
app_service_name = "test-app-service-ci-01"
location = "Central india"
vnet_name = "vnet-app-service-ci-01"
subnet_name = "snet-vnet-app-service-ci-app-01"
app_service_plan_id = "/subscriptions/XXXXXXX/resourceGroups/rg-app-service-ci-01/providers/Microsoft.Web/serverfarms/XXXXXXXX"
